version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ylab
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5438:5432"

  your_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: jdbc:postgresql://localhost:5438/ylab
    ports:
      - "8080:8080"
    command: sh -c "sleep 10 && java -jar target/Monitoring-Service.jar"