version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ylab
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"

  your_app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/ylab
    container_name: app
    command: ["java", "-jar", "out/artifacts/Monitoring_Service_jar2/Monitoring-Service.jar"]
    tty: true
    stdin_open: true
